# Generated by Django 5.0.1 on 2026-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('BALANCE_ALLOCATED', 'Balance Allocated'), ('BALANCE_ADJUSTED', 'Balance Adjusted'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('ATTENDANCE_CORRECTED', 'Attendance Corrected'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_DEACTIVATED', 'Employee Deactivated'), ('EMPLOYEE_ACTIVATED', 'Employee Activated'), ('HOLIDAY_CREATED', 'Holiday Created'), ('HOLIDAY_UPDATED', 'Holiday Updated'), ('HOLIDAY_DELETED', 'Holiday Deleted'), ('OTHER', 'Other Action')], help_text='Type of action performed', max_length=50)),
                ('model_name', models.CharField(help_text='Name of the model affected (e.g., LeaveRequest, Attendance)', max_length=50)),
                ('object_id', models.IntegerField(help_text='ID of the affected object')),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, help_text='Additional data (old/new values, reasons, etc.)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
