# Generated by Django 5.0.1 on 2026-02-09 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Leave type code (e.g., CL, SL, EL, LWP)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of leave type', max_length=50)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave type is paid')),
                ('requires_documentation', models.BooleanField(default=False, help_text='Whether attachment/documentation is required')),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed in one request', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of leave type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'leave_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date')),
                ('total_days', models.DecimalField(decimal_places=1, help_text='Total leave days (e.g., 1.5 for half-day)', max_digits=4)),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('attachment', models.FileField(blank=True, help_text='Optional supporting document', null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of leave request', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='When the request was submitted')),
                ('decision_at', models.DateTimeField(blank=True, help_text='When the decision was made', null=True)),
                ('manager_comments', models.TextField(blank=True, help_text='Manager comments on approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'db_table': 'leave_requests',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status'], name='leave_reque_status_401183_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_reque_start_d_08703b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Fiscal year (e.g., 2026)')),
                ('allocated', models.DecimalField(decimal_places=1, default=0, help_text='Total allocated leave days', max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0, help_text='Leave days used', max_digits=5)),
                ('adjusted', models.DecimalField(decimal_places=1, default=0, help_text='Manual adjustments by admin', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
                'ordering': ['employee', 'leave_type', '-year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
