# Generated by Django 5.0.1 on 2026-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('WFH', 'Work From Home'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent')], default='PRESENT', help_text='Attendance status', max_length=10)),
                ('is_self_marked', models.BooleanField(default=True, help_text='True if employee marked, False if admin marked/corrected')),
                ('correction_reason', models.TextField(blank=True, help_text='Reason for admin correction')),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='When attendance was initially marked')),
                ('corrected_at', models.DateTimeField(blank=True, help_text='When admin corrected the attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name (e.g., Independence Day)', max_length=200)),
                ('date', models.DateField(help_text='Holiday date', unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the holiday')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this is an optional holiday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
    ]
